/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as CriarContaRouteImport } from './routes/criar-conta'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppFilhaConquistasRouteImport } from './routes/app/filha/conquistas'
import { Route as AppFilhaHojeRouteImport } from './routes/app/filha/hoje'
import { Route as AppFilhaProgressoRouteImport } from './routes/app/filha/progresso'
import { Route as AppMaeDashboardRouteImport } from './routes/app/mae/dashboard'
import { Route as AppMaeFilhasRouteImport } from './routes/app/mae/filhas'
import { Route as AppMaeNotificacoesRouteImport } from './routes/app/mae/notificacoes'
import { Route as AppMaeRelatoriosRouteImport } from './routes/app/mae/relatorios'
import { Route as AppMaeTarefasRouteImport } from './routes/app/mae/tarefas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarContaRoute = CriarContaRouteImport.update({
  id: '/criar-conta',
  path: '/criar-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFilhaConquistasRoute = AppFilhaConquistasRouteImport.update({
  id: '/filha/conquistas',
  path: '/filha/conquistas',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFilhaHojeRoute = AppFilhaHojeRouteImport.update({
  id: '/filha/hoje',
  path: '/filha/hoje',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFilhaProgressoRoute = AppFilhaProgressoRouteImport.update({
  id: '/filha/progresso',
  path: '/filha/progresso',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMaeDashboardRoute = AppMaeDashboardRouteImport.update({
  id: '/mae/dashboard',
  path: '/mae/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMaeFilhasRoute = AppMaeFilhasRouteImport.update({
  id: '/mae/filhas',
  path: '/mae/filhas',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMaeNotificacoesRoute = AppMaeNotificacoesRouteImport.update({
  id: '/mae/notificacoes',
  path: '/mae/notificacoes',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMaeRelatoriosRoute = AppMaeRelatoriosRouteImport.update({
  id: '/mae/relatorios',
  path: '/mae/relatorios',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMaeTarefasRoute = AppMaeTarefasRouteImport.update({
  id: '/mae/tarefas',
  path: '/mae/tarefas',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/criar-conta': typeof CriarContaRoute
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/app/': typeof AppIndexRoute
  '/app/filha/conquistas': typeof AppFilhaConquistasRoute
  '/app/filha/hoje': typeof AppFilhaHojeRoute
  '/app/filha/progresso': typeof AppFilhaProgressoRoute
  '/app/mae/dashboard': typeof AppMaeDashboardRoute
  '/app/mae/filhas': typeof AppMaeFilhasRoute
  '/app/mae/notificacoes': typeof AppMaeNotificacoesRoute
  '/app/mae/relatorios': typeof AppMaeRelatoriosRoute
  '/app/mae/tarefas': typeof AppMaeTarefasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/criar-conta': typeof CriarContaRoute
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/app': typeof AppIndexRoute
  '/app/filha/conquistas': typeof AppFilhaConquistasRoute
  '/app/filha/hoje': typeof AppFilhaHojeRoute
  '/app/filha/progresso': typeof AppFilhaProgressoRoute
  '/app/mae/dashboard': typeof AppMaeDashboardRoute
  '/app/mae/filhas': typeof AppMaeFilhasRoute
  '/app/mae/notificacoes': typeof AppMaeNotificacoesRoute
  '/app/mae/relatorios': typeof AppMaeRelatoriosRoute
  '/app/mae/tarefas': typeof AppMaeTarefasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/criar-conta': typeof CriarContaRoute
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/app/': typeof AppIndexRoute
  '/app/filha/conquistas': typeof AppFilhaConquistasRoute
  '/app/filha/hoje': typeof AppFilhaHojeRoute
  '/app/filha/progresso': typeof AppFilhaProgressoRoute
  '/app/mae/dashboard': typeof AppMaeDashboardRoute
  '/app/mae/filhas': typeof AppMaeFilhasRoute
  '/app/mae/notificacoes': typeof AppMaeNotificacoesRoute
  '/app/mae/relatorios': typeof AppMaeRelatoriosRoute
  '/app/mae/tarefas': typeof AppMaeTarefasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/criar-conta'
    | '/login'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/app/'
    | '/app/filha/conquistas'
    | '/app/filha/hoje'
    | '/app/filha/progresso'
    | '/app/mae/dashboard'
    | '/app/mae/filhas'
    | '/app/mae/notificacoes'
    | '/app/mae/relatorios'
    | '/app/mae/tarefas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/criar-conta'
    | '/login'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/app'
    | '/app/filha/conquistas'
    | '/app/filha/hoje'
    | '/app/filha/progresso'
    | '/app/mae/dashboard'
    | '/app/mae/filhas'
    | '/app/mae/notificacoes'
    | '/app/mae/relatorios'
    | '/app/mae/tarefas'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/criar-conta'
    | '/login'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/app/'
    | '/app/filha/conquistas'
    | '/app/filha/hoje'
    | '/app/filha/progresso'
    | '/app/mae/dashboard'
    | '/app/mae/filhas'
    | '/app/mae/notificacoes'
    | '/app/mae/relatorios'
    | '/app/mae/tarefas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  CriarContaRoute: typeof CriarContaRoute
  LoginRoute: typeof LoginRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar-conta': {
      id: '/criar-conta'
      path: '/criar-conta'
      fullPath: '/criar-conta'
      preLoaderRoute: typeof CriarContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/filha/conquistas': {
      id: '/app/filha/conquistas'
      path: '/filha/conquistas'
      fullPath: '/app/filha/conquistas'
      preLoaderRoute: typeof AppFilhaConquistasRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/filha/hoje': {
      id: '/app/filha/hoje'
      path: '/filha/hoje'
      fullPath: '/app/filha/hoje'
      preLoaderRoute: typeof AppFilhaHojeRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/filha/progresso': {
      id: '/app/filha/progresso'
      path: '/filha/progresso'
      fullPath: '/app/filha/progresso'
      preLoaderRoute: typeof AppFilhaProgressoRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/mae/dashboard': {
      id: '/app/mae/dashboard'
      path: '/mae/dashboard'
      fullPath: '/app/mae/dashboard'
      preLoaderRoute: typeof AppMaeDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/mae/filhas': {
      id: '/app/mae/filhas'
      path: '/mae/filhas'
      fullPath: '/app/mae/filhas'
      preLoaderRoute: typeof AppMaeFilhasRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/mae/notificacoes': {
      id: '/app/mae/notificacoes'
      path: '/mae/notificacoes'
      fullPath: '/app/mae/notificacoes'
      preLoaderRoute: typeof AppMaeNotificacoesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/mae/relatorios': {
      id: '/app/mae/relatorios'
      path: '/mae/relatorios'
      fullPath: '/app/mae/relatorios'
      preLoaderRoute: typeof AppMaeRelatoriosRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/mae/tarefas': {
      id: '/app/mae/tarefas'
      path: '/mae/tarefas'
      fullPath: '/app/mae/tarefas'
      preLoaderRoute: typeof AppMaeTarefasRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppFilhaConquistasRoute: typeof AppFilhaConquistasRoute
  AppFilhaHojeRoute: typeof AppFilhaHojeRoute
  AppFilhaProgressoRoute: typeof AppFilhaProgressoRoute
  AppMaeDashboardRoute: typeof AppMaeDashboardRoute
  AppMaeFilhasRoute: typeof AppMaeFilhasRoute
  AppMaeNotificacoesRoute: typeof AppMaeNotificacoesRoute
  AppMaeRelatoriosRoute: typeof AppMaeRelatoriosRoute
  AppMaeTarefasRoute: typeof AppMaeTarefasRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppFilhaConquistasRoute: AppFilhaConquistasRoute,
  AppFilhaHojeRoute: AppFilhaHojeRoute,
  AppFilhaProgressoRoute: AppFilhaProgressoRoute,
  AppMaeDashboardRoute: AppMaeDashboardRoute,
  AppMaeFilhasRoute: AppMaeFilhasRoute,
  AppMaeNotificacoesRoute: AppMaeNotificacoesRoute,
  AppMaeRelatoriosRoute: AppMaeRelatoriosRoute,
  AppMaeTarefasRoute: AppMaeTarefasRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  CriarContaRoute: CriarContaRoute,
  LoginRoute: LoginRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
